name : CI_release

on:
    release:
        types: [released]
    workflow_dispatch:

env: 
    AZURE_RG_NAME: ${{ vars.PROJECT_NAME }}-rg-${{ vars.AZURE_RESOURCE_IDENTIFIER }}

jobs:
    build_backend:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build the app
              run: dotnet build -c Release --property:PublishDir=./backend/ParkNDeploy.Api/publish # Ensure the publish directory is correctly specified
              working-directory: ./backend # specify where to find the solution file
            - name: Verify publish directory
              run: ls -la ./backend/ParkNDeploy.Api/publish # Verify that the publish directory contains files
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: backend-artifact
                path: ./backend/ParkNDeploy.Api/publish

    build_frontend:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build the app
          run: npm install && npm run build
          working-directory: ./frontend

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
                name: frontend-artifact
                path: ./frontend/dist

    call_cd_workflow:
      needs: [build_backend, build_frontend]
      permissions:
          id-token: write # Require write permission to Fetch an OIDC token (required for federated credential)
      uses: daxterman/parkndeploy/.github/workflows/CD-release.yml@main
      secrets: inherit
